spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/carsharing?serverTimezone=UTC
    username: root
    password: maloi-26
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: db.changelog/db.changelog-master.xml
  mvc:
    view:
      prefix: /WEB-INF/templates/
      suffix: .html

log:
  file:
    path: log.file.path= D:\\

security:
  jwt:
    secretKey: apple
    expirationToken: 86400000

server:
  servlet:
    session:
      cookie:
        max-age: 86400000
---
