USE `carsharing`;
GO
DELETE FROM `deal`
GO
DELETE FROM `card`
GO
DELETE FROM `customer_role`
GO
DELETE FROM `car`
GO
DELETE FROM `customer`
GO
DELETE FROM `specialist`
GO
DELETE FROM `role`
GO
DELETE FROM `rate`
GO
ALTER TABLE `deal` DROP COLUMN `date`;
GO
ALTER TABLE `deal` ADD `start_date` TIMESTAMP NOT NULL
GO
ALTER TABLE `deal` ADD `end_date` TIMESTAMP NULL
GO
ALTER TABLE `deal` ADD receipt BLOB;
GO
ALTER TABLE `customer` ADD `balance` NUMERIC(15, 2) DEFAULT 0
GO
ALTER TABLE `car` ADD `posX` DECIMAL(11, 8)
GO
ALTER TABLE `car` ADD `posY` DECIMAL(11, 8)
GO
ALTER TABLE `car` ADD `doorStatus` VARCHAR(255)